-- Genres data for SOPDS
-- Ported from MySQL genres.sql


INSERT INTO genres(genre,subsection,section) values('economics_ref','Деловая литература','Деловая литература');
INSERT INTO genres(genre,subsection,section) values('popular_business','Карьера, кадры','Деловая литература');
INSERT INTO genres(genre,subsection,section) values('org_behavior','Маркетинг, PR','Деловая литература');
INSERT INTO genres(genre,subsection,section) values('banking','Финансы','Деловая литература');
INSERT INTO genres(genre,subsection,section) values('economics','Экономика','Деловая литература');
INSERT INTO genres(genre,subsection,section) values('det_action','Боевик','Детективы и Триллеры');
INSERT INTO genres(genre,subsection,section) values('detective','Детективы','Детективы и Триллеры');
INSERT INTO genres(genre,subsection,section) values('det_irony','Иронический детектив, дамский детективный роман','Детективы и Триллеры');
INSERT INTO genres(genre,subsection,section) values('det_history','Исторический детектив','Детективы и Триллеры');
INSERT INTO genres(genre,subsection,section) values('det_classic','Классический детектив','Детективы и Триллеры');
INSERT INTO genres(genre,subsection,section) values('det_crime','Криминальный детектив','Детективы и Триллеры');
INSERT INTO genres(genre,subsection,section) values('det_hard','Крутой детектив','Детективы и Триллеры');
INSERT INTO genres(genre,subsection,section) values('det_political','Политический детектив','Детективы и Триллеры');
INSERT INTO genres(genre,subsection,section) values('det_police','Полицейский детектив','Детективы и Триллеры');
INSERT INTO genres(genre,subsection,section) values('det_maniac','Про маньяков','Детективы и Триллеры');
INSERT INTO genres(genre,subsection,section) values('det_su','Советский детектив','Детективы и Триллеры');
INSERT INTO genres(genre,subsection,section) values('thriller','Триллер','Детективы и Триллеры');
INSERT INTO genres(genre,subsection,section) values('det_espionage','Шпионский детектив','Детективы и Триллеры');
INSERT INTO genres(genre,subsection,section) values('nonf_biography','Биографии и Мемуары','Документальная литература');
INSERT INTO genres(genre,subsection,section) values('nonf_military','Военная документалистика и аналитика','Документальная литература');
INSERT INTO genres(genre,subsection,section) values('military_special','Военное дело','Документальная литература');
INSERT INTO genres(genre,subsection,section) values('travel_notes','География, путевые заметки','Документальная литература');
INSERT INTO genres(genre,subsection,section) values('nonfiction','Документальная литература','Документальная литература');
INSERT INTO genres(genre,subsection,section) values('nonf_publicism','Публицистика','Документальная литература');
INSERT INTO genres(genre,subsection,section) values('auto_regulations','Автомобили и ПДД','Дом и семья');
INSERT INTO genres(genre,subsection,section) values('home_sport','Боевые искусства, спорт','Дом и семья');
INSERT INTO genres(genre,subsection,section) values('home_pets','Домашние животные','Дом и семья');
INSERT INTO genres(genre,subsection,section) values('home','Домоводство','Дом и семья');
INSERT INTO genres(genre,subsection,section) values('home_health','Здоровье','Дом и семья');
INSERT INTO genres(genre,subsection,section) values('home_collecting','Коллекционирование','Дом и семья');
INSERT INTO genres(genre,subsection,section) values('home_cooking','Кулинария','Дом и семья');
INSERT INTO genres(genre,subsection,section) values('sci_pedagogy','Педагогика, воспитание детей, литература для родителей','Дом и семья');
INSERT INTO genres(genre,subsection,section) values('home_entertain','Развлечения','Дом и семья');
INSERT INTO genres(genre,subsection,section) values('home_garden','Сад и огород','Дом и семья');
INSERT INTO genres(genre,subsection,section) values('home_diy','Сделай сам','Дом и семья');
INSERT INTO genres(genre,subsection,section) values('family','Семейные отношения','Дом и семья');
INSERT INTO genres(genre,subsection,section) values('home_sex','Семейные отношения, секс','Дом и семья');
INSERT INTO genres(genre,subsection,section) values('home_crafts','Хобби и ремесла','Дом и семья');
INSERT INTO genres(genre,subsection,section) values('drama_antique','Античная драма','Драматургия');
INSERT INTO genres(genre,subsection,section) values('drama','Драма','Драматургия');
INSERT INTO genres(genre,subsection,section) values('dramaturgy','Драматургия','Драматургия');
INSERT INTO genres(genre,subsection,section) values('comedy','Комедия','Драматургия');
INSERT INTO genres(genre,subsection,section) values('vaudeville','Мистерия, буффонада, водевиль','Драматургия');
INSERT INTO genres(genre,subsection,section) values('screenplays','Сценарий','Драматургия');
INSERT INTO genres(genre,subsection,section) values('tragedy','Трагедия','Драматургия');
INSERT INTO genres(genre,subsection,section) values('painting','Живопись, альбомы, иллюстрированные каталоги','Искусство, Искусствоведение, Дизайн');
INSERT INTO genres(genre,subsection,section) values('design','Искусство и Дизайн','Искусство, Искусствоведение, Дизайн');
INSERT INTO genres(genre,subsection,section) values('art_criticism','Искусствоведение','Искусство, Искусствоведение, Дизайн');
INSERT INTO genres(genre,subsection,section) values('cine','Кино','Искусство, Искусствоведение, Дизайн');
INSERT INTO genres(genre,subsection,section) values('nonf_criticism','Критика','Искусство, Искусствоведение, Дизайн');
INSERT INTO genres(genre,subsection,section) values('sci_culture','Культурология','Искусство, Искусствоведение, Дизайн');
INSERT INTO genres(genre,subsection,section) values('art_world_culture','Мировая художественная культура','Искусство, Искусствоведение, Дизайн');
INSERT INTO genres(genre,subsection,section) values('music','Музыка','Искусство, Искусствоведение, Дизайн');
INSERT INTO genres(genre,subsection,section) values('notes','Партитуры','Искусство, Искусствоведение, Дизайн');
INSERT INTO genres(genre,subsection,section) values('architecture_book','Скульптура и архитектура','Искусство, Искусствоведение, Дизайн');
INSERT INTO genres(genre,subsection,section) values('theatre','Театр','Искусство, Искусствоведение, Дизайн');
INSERT INTO genres(genre,subsection,section) values('computers','Зарубежная компьютерная, околокомпьютерная литература','Компьютеры и Интернет');
INSERT INTO genres(genre,subsection,section) values('comp_hard','аппаратное обеспечение, цифровая обработка сигналов, Компьютерное ''железо''','Компьютеры и Интернет');
INSERT INTO genres(genre,subsection,section) values('comp_www','ОС и Сети, интернет','Компьютеры и Интернет');
INSERT INTO genres(genre,subsection,section) values('comp_db','Программирование, программы, базы данных','Компьютеры и Интернет');
INSERT INTO genres(genre,subsection,section) values('tbg_computers','Учебные пособия, самоучители','Компьютеры и Интернет');
INSERT INTO genres(genre,subsection,section) values('children','Детская литература','Литература для детей');
INSERT INTO genres(genre,subsection,section) values('child_education','Детская образовательная литература','Литература для детей');
INSERT INTO genres(genre,subsection,section) values('child_det','Детская остросюжетная литература','Литература для детей');
INSERT INTO genres(genre,subsection,section) values('foreign_children','Зарубежная литература для детей','Литература для детей');
INSERT INTO genres(genre,subsection,section) values('prose_game','Игры, упражнения для детей','Литература для детей');
INSERT INTO genres(genre,subsection,section) values('child_classical','Классическая детская литература','Литература для детей');
INSERT INTO genres(genre,subsection,section) values('child_prose','Проза для детей','Литература для детей');
INSERT INTO genres(genre,subsection,section) values('child_tale_rus','Русские сказки','Литература для детей');
INSERT INTO genres(genre,subsection,section) values('child_tale','Сказки народов мира','Литература для детей');
INSERT INTO genres(genre,subsection,section) values('child_verse','Стихи для детей','Литература для детей');
INSERT INTO genres(genre,subsection,section) values('child_sf','Фантастика для детей','Литература для детей');
INSERT INTO genres(genre,subsection,section) values('love_history','Исторические любовные романы','Любовные романы');
INSERT INTO genres(genre,subsection,section) values('love_short','Короткие любовные романы','Любовные романы');
INSERT INTO genres(genre,subsection,section) values('love_sf','Любовное фэнтези, любовно-фантастические романы','Любовные романы');
INSERT INTO genres(genre,subsection,section) values('love','Любовные романы','Любовные романы');
INSERT INTO genres(genre,subsection,section) values('love_detective','Остросюжетные любовные романы','Любовные романы');
INSERT INTO genres(genre,subsection,section) values('love_hard','Порно','Любовные романы');
INSERT INTO genres(genre,subsection,section) values('love_contemporary','Современные любовные романы','Любовные романы');
INSERT INTO genres(genre,subsection,section) values('love_erotica','Эротическая литература','Любовные романы');
INSERT INTO genres(genre,subsection,section) values('sci_medicine_alternative','Альтернативная медицина','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_theories','Альтернативные науки и научные теории','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_cosmos','Астрономия и Космос','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_biology','Биология, биофизика, биохимия','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_botany','Ботаника','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_veterinary','Ветеринария','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('military_history','Военная история','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_oriental','Востоковедение','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_geo','Геология и география','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_state','Государство и право','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_popular','Зарубежная образовательная литература, зарубежная прикладная, научно-популярная литература','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_zoo','Зоология','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_history','История','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_philology','Литературоведение','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_math','Математика','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_medicine','Медицина','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('science','Научная литература','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_social_studies','Обществознание, социология','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_politics','Политика','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_psychology','Психология и психотерапия','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_phys','Физика','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_philosophy','Философия','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_chem','Химия','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_ecology','Экология','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_economy','Экономика','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_juris','Юриспруденция','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('sci_linguistic','Языкознание, иностранные языки','Наука, Образование');
INSERT INTO genres(genre,subsection,section) values('palindromes','Визуальная и экспериментальная поэзия, верлибры, палиндромы','Поэзия');
INSERT INTO genres(genre,subsection,section) values('poetry_for_classical','Классическая зарубежная поэзия','Поэзия');
INSERT INTO genres(genre,subsection,section) values('poetry_classical','Классическая поэзия','Поэзия');
INSERT INTO genres(genre,subsection,section) values('poetry_rus_classical','Классическая русская поэзия','Поэзия');
INSERT INTO genres(genre,subsection,section) values('lyrics','Лирика','Поэзия');
INSERT INTO genres(genre,subsection,section) values('song_poetry','Песенная поэзия','Поэзия');
INSERT INTO genres(genre,subsection,section) values('poetry','Поэзия','Поэзия');
INSERT INTO genres(genre,subsection,section) values('poetry_east','Поэзия Востока','Поэзия');
INSERT INTO genres(genre,subsection,section) values('poem','Поэма, эпическая поэзия','Поэзия');
INSERT INTO genres(genre,subsection,section) values('poetry_for_modern','Современная зарубежная поэзия','Поэзия');
INSERT INTO genres(genre,subsection,section) values('poetry_modern','Современная поэзия','Поэзия');
INSERT INTO genres(genre,subsection,section) values('poetry_rus_modern','Современная русская поэзия','Поэзия');
INSERT INTO genres(genre,subsection,section) values('humor_verse','Юмористические стихи, басни','Поэзия');
INSERT INTO genres(genre,subsection,section) values('adv_story','Авантюрный роман','Приключения');
INSERT INTO genres(genre,subsection,section) values('adv_indian','Вестерн, про индейцев','Приключения');
INSERT INTO genres(genre,subsection,section) values('adv_history','Исторические приключения','Приключения');
INSERT INTO genres(genre,subsection,section) values('adv_maritime','Морские приключения','Приключения');
INSERT INTO genres(genre,subsection,section) values('adventure','Приключения','Приключения');
INSERT INTO genres(genre,subsection,section) values('adv_modern','Приключения в современном мире','Приключения');
INSERT INTO genres(genre,subsection,section) values('child_adv','Приключения для детей и подростков','Приключения');
INSERT INTO genres(genre,subsection,section) values('adv_animal','Природа и животные','Приключения');
INSERT INTO genres(genre,subsection,section) values('adv_geo','Путешествия и география','Приключения');
INSERT INTO genres(genre,subsection,section) values('tale_chivalry','Рыцарский роман','Приключения');
INSERT INTO genres(genre,subsection,section) values('aphorisms','Афоризмы, цитаты','Проза');
INSERT INTO genres(genre,subsection,section) values('gothic_novel','Готический роман','Проза');
INSERT INTO genres(genre,subsection,section) values('foreign_prose','Зарубежная классическая проза','Проза');
INSERT INTO genres(genre,subsection,section) values('prose_history','Историческая проза','Проза');
INSERT INTO genres(genre,subsection,section) values('prose_classic','Классическая проза','Проза');
INSERT INTO genres(genre,subsection,section) values('literature_18','Классическая проза XVII-XVIII веков','Проза');
INSERT INTO genres(genre,subsection,section) values('literature_19','Классическая проза ХIX века','Проза');
INSERT INTO genres(genre,subsection,section) values('literature_20','Классическая проза ХX века','Проза');
INSERT INTO genres(genre,subsection,section) values('prose_counter','Контркультура','Проза');
INSERT INTO genres(genre,subsection,section) values('prose_magic','Магический реализм','Проза');
INSERT INTO genres(genre,subsection,section) values('story','Малые литературные формы прозы: рассказы, эссе, новеллы, феерия','Проза');
INSERT INTO genres(genre,subsection,section) values('prose','Проза','Проза');
INSERT INTO genres(genre,subsection,section) values('prose_military','Проза о войне','Проза');
INSERT INTO genres(genre,subsection,section) values('great_story','Роман, повесть','Проза');
INSERT INTO genres(genre,subsection,section) values('prose_rus_classic','Русская классическая проза','Проза');
INSERT INTO genres(genre,subsection,section) values('prose_su_classics','Советская классическая проза','Проза');
INSERT INTO genres(genre,subsection,section) values('prose_contemporary','Современная русская и зарубежная проза','Проза');
INSERT INTO genres(genre,subsection,section) values('foreign_antique','Средневековая классическая проза','Проза');
INSERT INTO genres(genre,subsection,section) values('prose_abs','Фантасмагория, абсурдистская проза','Проза');
INSERT INTO genres(genre,subsection,section) values('prose_neformatny','Экспериментальная, неформатная проза','Проза');
INSERT INTO genres(genre,subsection,section) values('epistolary_fiction','Эпистолярная проза','Проза');
INSERT INTO genres(genre,subsection,section) values('periodic','Журналы, газеты','Прочее');
INSERT INTO genres(genre,subsection,section) values('comics','Комиксы','Прочее');
INSERT INTO genres(genre,subsection,section) values('unfinished','Незавершенное','Прочее');
INSERT INTO genres(genre,subsection,section) values('other','Неотсортированное','Прочее');
INSERT INTO genres(genre,subsection,section) values('network_literature','Самиздат, сетевая литература','Прочее');
INSERT INTO genres(genre,subsection,section) values('fanfiction','Фанфик','Прочее');
INSERT INTO genres(genre,subsection,section) values('astrology','Астрология и хиромантия','Религия, духовность, эзотерика');
INSERT INTO genres(genre,subsection,section) values('religion_budda','Буддизм','Религия, духовность, эзотерика');
INSERT INTO genres(genre,subsection,section) values('religion_hinduism','Индуизм','Религия, духовность, эзотерика');
INSERT INTO genres(genre,subsection,section) values('religion_islam','Ислам','Религия, духовность, эзотерика');
INSERT INTO genres(genre,subsection,section) values('religion_judaism','Иудаизм','Религия, духовность, эзотерика');
INSERT INTO genres(genre,subsection,section) values('religion_catholicism','Католицизм','Религия, духовность, эзотерика');
INSERT INTO genres(genre,subsection,section) values('religion_orthodoxy','Православие','Религия, духовность, эзотерика');
INSERT INTO genres(genre,subsection,section) values('religion_protestantism','Протестантизм','Религия, духовность, эзотерика');
INSERT INTO genres(genre,subsection,section) values('sci_religion','Религиоведение','Религия, духовность, эзотерика');
INSERT INTO genres(genre,subsection,section) values('religion','Религия, религиозная литература','Религия, духовность, эзотерика');
INSERT INTO genres(genre,subsection,section) values('religion_self','Самосовершенствование','Религия, духовность, эзотерика');
INSERT INTO genres(genre,subsection,section) values('religion_christianity','Христианство','Религия, духовность, эзотерика');
INSERT INTO genres(genre,subsection,section) values('religion_esoterics','Эзотерика, эзотерическая литература','Религия, духовность, эзотерика');
INSERT INTO genres(genre,subsection,section) values('religion_paganism','Язычество','Религия, духовность, эзотерика');
INSERT INTO genres(genre,subsection,section) values('geo_guides','Путеводители, карты, атласы','Справочная литература');
INSERT INTO genres(genre,subsection,section) values('ref_guide','Руководства','Справочная литература');
INSERT INTO genres(genre,subsection,section) values('ref_dict','Словари','Справочная литература');
INSERT INTO genres(genre,subsection,section) values('reference','Справочная литература','Справочная литература');
INSERT INTO genres(genre,subsection,section) values('ref_ref','Справочники','Справочная литература');
INSERT INTO genres(genre,subsection,section) values('ref_encyc','Энциклопедии','Справочная литература');
INSERT INTO genres(genre,subsection,section) values('antique','antique','Старинное');
INSERT INTO genres(genre,subsection,section) values('antique_ant','Античная литература','Старинное');
INSERT INTO genres(genre,subsection,section) values('antique_east','Древневосточная литература','Старинное');
INSERT INTO genres(genre,subsection,section) values('antique_russian','Древнерусская литература','Старинное');
INSERT INTO genres(genre,subsection,section) values('antique_european','Европейская старинная литература','Старинное');
INSERT INTO genres(genre,subsection,section) values('auto_business','Автодело','Техника');
INSERT INTO genres(genre,subsection,section) values('military_weapon','Военное дело, военная техника и вооружение','Техника');
INSERT INTO genres(genre,subsection,section) values('equ_history','История техники','Техника');
INSERT INTO genres(genre,subsection,section) values('sci_metal','Металлургия','Техника');
INSERT INTO genres(genre,subsection,section) values('sci_radio','Радиоэлектроника','Техника');
INSERT INTO genres(genre,subsection,section) values('sci_build','Строительство и сопромат','Техника');
INSERT INTO genres(genre,subsection,section) values('sci_tech','Технические науки','Техника');
INSERT INTO genres(genre,subsection,section) values('sci_transport','Транспорт и авиация','Техника');
INSERT INTO genres(genre,subsection,section) values('sci_textbook','Учебники и пособия','Учебники и пособия');
INSERT INTO genres(genre,subsection,section) values('tbg_higher','Учебники и пособия ВУЗов','Учебники и пособия');
INSERT INTO genres(genre,subsection,section) values('tbg_secondary','Учебники и пособия для среднего и специального образования','Учебники и пособия');
INSERT INTO genres(genre,subsection,section) values('tbg_school','Школьные учебники и пособия, рефераты, шпаргалки','Учебники и пособия');
INSERT INTO genres(genre,subsection,section) values('sf_history','Альтернативная история, попаданцы','Фантастика');
INSERT INTO genres(genre,subsection,section) values('sf_action','Боевая фантастика','Фантастика');
INSERT INTO genres(genre,subsection,section) values('sf_heroic','Героическая фантастика','Фантастика');
INSERT INTO genres(genre,subsection,section) values('sf_fantasy_city','Городское фэнтези','Фантастика');
INSERT INTO genres(genre,subsection,section) values('sf_detective','Детективная фантастика','Фантастика');
INSERT INTO genres(genre,subsection,section) values('sf_cyberpunk','Киберпанк','Фантастика');
INSERT INTO genres(genre,subsection,section) values('sf_space','Космическая фантастика','Фантастика');
INSERT INTO genres(genre,subsection,section) values('sf_mystic','Мистика','Фантастика');
INSERT INTO genres(genre,subsection,section) values('fairy_fantasy','Мифологическое фэнтези','Фантастика');
INSERT INTO genres(genre,subsection,section) values('sf','Научная Фантастика','Фантастика');
INSERT INTO genres(genre,subsection,section) values('sf_postapocalyptic','Постапокалипсис','Фантастика');
INSERT INTO genres(genre,subsection,section) values('russian_fantasy','Славянское фэнтези','Фантастика');
INSERT INTO genres(genre,subsection,section) values('modern_tale','Современная сказка','Фантастика');
INSERT INTO genres(genre,subsection,section) values('sf_social','Социально-психологическая фантастика','Фантастика');
INSERT INTO genres(genre,subsection,section) values('sf_stimpank','Стимпанк','Фантастика');
INSERT INTO genres(genre,subsection,section) values('sf_technofantasy','Технофэнтези','Фантастика');
INSERT INTO genres(genre,subsection,section) values('sf_horror','Ужасы','Фантастика');
INSERT INTO genres(genre,subsection,section) values('sf_etc','Фантастика','Фантастика');
INSERT INTO genres(genre,subsection,section) values('sf_fantasy','Фэнтези','Фантастика');
INSERT INTO genres(genre,subsection,section) values('hronoopera','Хроноопера','Фантастика');
INSERT INTO genres(genre,subsection,section) values('sf_epic','Эпическая фантастика','Фантастика');
INSERT INTO genres(genre,subsection,section) values('sf_humor','Юмористическая фантастика','Фантастика');
INSERT INTO genres(genre,subsection,section) values('epic','Былины, эпопея','Фольклор');
INSERT INTO genres(genre,subsection,section) values('child_folklore','Детский фольклор','Фольклор');
INSERT INTO genres(genre,subsection,section) values('antique_myths','Мифы. Легенды. Эпос','Фольклор');
INSERT INTO genres(genre,subsection,section) values('folk_songs','Народные песни','Фольклор');
INSERT INTO genres(genre,subsection,section) values('folk_tale','Народные сказки','Фольклор');
INSERT INTO genres(genre,subsection,section) values('proverbs','Пословицы, поговорки','Фольклор');
INSERT INTO genres(genre,subsection,section) values('folklore','Фольклор, загадки folklore','Фольклор');
INSERT INTO genres(genre,subsection,section) values('limerick','Частушки, прибаутки, потешки','Фольклор');
INSERT INTO genres(genre,subsection,section) values('humor_anecdote','Анекдоты','Юмор');
INSERT INTO genres(genre,subsection,section) values('humor_satire','Сатира','Юмор');
INSERT INTO genres(genre,subsection,section) values('humor','Юмор','Юмор');
INSERT INTO genres(genre,subsection,section) values('humor_prose','Юмористическая проза','Юмор');
commit;
